#!/usr/bin/env ruby

# Modified from: http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen

git_bundles = [ 
  "git://github.com/tpope/vim-pathogen.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/henrik/vim-indexed-search.git",
  "git://github.com/othree/html5.vim.git",
  "git://github.com/plasticboy/vim-markdown.git",
  "git://github.com/timcharper/textile.vim.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/digitaltoad/vim-jade.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-rvm.git",
  "git://github.com/tpope/vim-commentary.git",
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tsaleh/vim-shoulda.git",
  "git://github.com/wavded/vim-stylus.git",
  "git://github.com/duskhacker/sweet-rspec-vim.git",
  "git://github.com/itspriddle/vim-jquery.git",
  "git://github.com/tsaleh/vim-align.git",
  "git://github.com/tsaleh/vim-supertab.git",
  "git://github.com/vim-scripts/browser.vim--Brown.git",
  "git://github.com/pangloss/vim-javascript.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/wincent/Command-T.git",
  "git://github.com/scrooloose/nerdtree.git",
  "git://github.com/vim-ruby/vim-ruby.git",
  "git://github.com/leshill/vim-json.git",
  "git://github.com/tsaleh/vim-tcomment.git",
  "git://github.com/mattn/gist-vim.git",
  "git://github.com/msanders/snipmate.vim.git",
  "git://github.com/briancollins/vim-jst.git",
  "git://github.com/tpope/vim-vividchalk.git"
]

vim_org_scripts = [
  # ["IndexedSearch", "7062",  "plugin"],
  # ["gist",          "12732", "plugin"],
  # ["jquery",        "12107", "syntax"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "Trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  if script_type == 'zip'
    local_file = File.join(name, "#{name}.#{script_type}")
  else
    local_file = File.join(name, script_type, "#{name}.vim")
  end
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
  if script_type == 'zip'
    `unzip #{local_file} -d #{name}`
    FileUtils.rm_rf(local_file)
  end
end